### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by clarzou** [cytronn/HETIC-G1-08#33]
Commandes
- [x] confirmation email
- [x] decrement dish quantity before payment is validated (avoid that another user orders a non available dish )

Organisations
- [x]  Create model
- [x] Create relation between organization and user
- [x] Add organization to validate user creation
- [x]  Create new organization on user registration
- [x] Add select on user registration form with existing organizations
- [x] Only show dishes according to the users organizations

Front BS
- [x]  Signup
- [x]  Sign in 
- [x] Create dish
- [x] Edit dish
- [ ] ...  

Filters
- [x] Date filters
- [x] Date separators on dish index
- [ ] Filter "hurry up" 

Content
- [ ] Home page content administrated by active admin
